# Generated by Django 3.1.1 on 2020-09-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='sku',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
